# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      - name: AppInspector
  uses: microsoft/ApplicationInspector-Action@v1
  with:
    # The path relative to repository root to scan.
    location-to-scan: # optional, default is GITHUB_WORKSPACE
    # The path relative to file root to output to.
    output-path: # optional, default is AppInspectorResults
    # Output format [html|json|text]
    output-format: # optional, default is json
    # Comma separated list of file path patterns to exclude.
    file-path-exclusions: # optional, default is ,
    # Other arguments to Application AppInspector
    arguments: # optional, default is 

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
